import { memo } from "react";
import type { PhotoData } from "../types/PhotoData";
import styles from "../styles/Gallery.module.css";

// --- Memoized integration time calculation ---
const integrationTimeCache = new WeakMap<PhotoData, number>();
// thumbnails are now generated by generate-thumbnails.cjs and stored in public/images/thumbnails
const calculateTotalIntegrationTime = (photo: PhotoData) => {
  if (integrationTimeCache.has(photo)) return integrationTimeCache.get(photo)!;
  if (!photo.integrationTimes) return 0;
  const total = Object.values(photo.integrationTimes).reduce((sum, time) => {
    if (time) return sum + time.numberOfPhotos * time.timePerPhoto;
    return sum;
  }, 0);
  integrationTimeCache.set(photo, total);
  return total;
};

const formatIntegrationTime = (time: number) => {
  const hours = Math.floor(time / 3600);
  const minutes = Math.floor((time % 3600) / 60);
  return `${hours}h ${minutes}min`;
};

// --- Memoized PhotoCard component ---
interface PhotoCardProps {
  photo: PhotoData;
  onClick: () => void;
}
const PhotoCard = memo(({ photo, onClick }: PhotoCardProps) => {
  // Prefer an explicit thumbnail filename, otherwise assume a thumbnail with the same base name (jpg) exists in thumbnails.
  const thumbFile =
    photo.thumbnailFileName || photo.fileName.replace(/\.[^/.]+$/, ".jpg");
  const thumbSrc = `./images/thumbnails/${thumbFile}`;

  return (
    <div className={styles.photoCard} onClick={onClick}>
      <img
        src={thumbSrc}
        alt={photo.objectName}
        loading="lazy"
        onError={(e) => {
          // fallback to the original file if thumbnail is missing
          (e.currentTarget as HTMLImageElement).src = `./images/${photo.fileName}`;
        }}
      />
      <div className={styles.photoInfo}>
        <h3>{photo.objectName}</h3>
        <p>{formatIntegrationTime(calculateTotalIntegrationTime(photo))}</p>
        <p>{photo.equipment.filters.join(", ")}</p>
      </div>
    </div>
  );
});

export default PhotoCard;
